# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Source
    displayName: Source code management
    jobs:
    - job: Format
      displayName: Format source code
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self
        - task: DotNetCoreCLI@2
          inputs:
            command: 'custom'
            custom: 'tool'
            arguments: 'restore'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'custom'
            custom: 'csharpier'
            arguments: '.'
        - task: CmdLine@2
          inputs:
            script: |
              git config --global user.email "zhangyue.dev@outlook.com"
              git config --global user.name "kamasylvia"
              git add -A
              git commit -m "Format source code with CSharpier"
    - job: Sync
      displayName: Push back to GitHub repository
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self
        - task: CmdLine@2
          inputs:
            script: |
              git push
  - stage: Deploy
    displayName: Deploy to production
    jobs:
    - job: Containerization
      displayName: Build image and push to DockerHub
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            additionalDockerComposeFiles: 'docker-compose.override.yml'
            action: 'Build services'
            includeLatestTag: true
            nopIfNoDockerComposeFile: true
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'DockerHub'
            dockerComposeFile: '**/docker-compose.yml'
            additionalDockerComposeFiles: 'docker-compose.override.yml'
            action: 'Push services'
            includeLatestTag: true
            nopIfNoDockerComposeFile: true
