# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: 'DockerHub'
          dockerComposeFile: '**/docker-compose.yml'
          additionalDockerComposeFiles: 'docker-compose.override.yml'
          action: 'Build services'
          includeLatestTag: true
          nopIfNoDockerComposeFile: true
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: 'DockerHub'
          dockerComposeFile: '**/docker-compose.yml'
          additionalDockerComposeFiles: 'docker-compose.override.yml'
          action: 'Push services'
          includeLatestTag: true
          nopIfNoDockerComposeFile: true
      - task: DotNetCoreCLI@2
        inputs:
          command: 'custom'
          custom: 'tool'
          arguments: 'restore'
      - task: CmdLine@2
        inputs:
          script: 'dotnet-csharpier'