version: "3.4"

services:
    redis:
        image: redis:alpine
        # ports:
        # - "5379:6379"
    eplusactivities-db:
        image: mysql:8.0.25
        container_name: MySQL-EPlusActivities
        ports:
            - 30303:3306
        environment:
            MYSQL_DATABASE: EPlusActivities
            MYSQL_USER: ngs
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TZ: Asia/Shanghai
        volumes:
            - ./MySQL/EPlusActivities:/var/lib/mysql
        restart: always

    eplusactivities-api:
        image: kamasylvia/eplusactivities:20211117
        container_name: EplusActivities.API
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        depends_on:
            - eplusactivities-db
        links:
            - eplusactivities-db
        # ports:
        #     - 52539:80
        volumes:
            - ./Logs/ApiLogs:/app/Logs
            - ./Settings/EplusActivities.API/appsettings.json:/app/appsettings.json
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        restart: always
    eplusactivities-sidecar:
        image: daprio/daprd:edge
        container_name: EplusActivities-Sidecar
        command:
            [
                "./daprd",
                "-app-id",
                "EPlusActivities",
                "-app-port",
                "80",
                "-components-path",
                "/components",
                # "-config",
                # "/configurations/config.yaml",
            ]
        volumes:
            - ./Dapr/Components/:/components
            - ./Dapr/Configurations/:/configurations
        depends_on:
            - "eplusactivities-api"
        network_mode: service:eplusactivities-api
        restart: always

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 52537:52537
        links:
            - "eplusactivities-api"
        volumes:
            - ./Nginx/conf.d:/etc/nginx/conf.d
            - ./html:/usr/share/nginx/html
            - ./Logs/NginxLogs:/var/log/nginx
        restart: always

    fileservice-db:
        image: mysql:8.0.25
        container_name: MySQL-FileService
        ports:
            - 30304:3306
        environment:
            MYSQL_DATABASE: FileService
            MYSQL_USER: ngs
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TZ: Asia/Shanghai
        volumes:
            - ./MySQL/FileService:/var/lib/mysql
        restart: always

    fileservice:
        image: kamasylvia/fileservice:20211110
        container_name: FileService
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:52500
        ports:
            - 50002:50002
        links:
            - fileservice-db
        depends_on:
            - fileservice-db
        volumes:
            - ./Logs/FileServiceLogs:/app/Logs
            - ./Settings/FileService/appsettings.json:/app/appsettings.json
            - ./FileStorage:/app/FileStorage
        restart: always
    fileservice-sidecar:
        image: daprio/daprd:edge
        container_name: FileService-Sidecar
        command:
            [
                "./daprd",
                "-app-id",
                "FileService",
                "-app-port",
                "52500",
                "-dapr-grpc-port",
                "50002",
                "-app-protocol",
                "grpc",
                "-components-path",
                "/components",
                # "-config",
                # "/configurations/config.yaml",
            ]
        volumes:
            - ./Dapr/Components/:/components
            - ./Dapr/Configurations/:/configurations
        depends_on:
            - "fileservice"
        network_mode: service:fileservice
        restart: always
