version: "3.4"

services:
    ############################
    # EPlusActivities service
    ############################
    eplusactivities-db:
        image: mysql:8.0.25
        container_name: MySQL-EPlusActivities
        ports:
            - 30303:3306
        environment:
            MYSQL_DATABASE: EPlusActivities
            MYSQL_USER: ngs
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TZ: Asia/Shanghai
        volumes:
            - ./MySQL/EPlusActivities:/var/lib/mysql
        networks:
            - network-dapr
        restart: always

    eplusactivities-api:
        image: kamasylvia/eplusactivities:20211203
        container_name: EplusActivities.API
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
        depends_on:
            - eplusactivities-db
            - placement
        links:
            - eplusactivities-db
        volumes:
            - ./Logs/ApiLogs:/app/Logs
            - ./Settings/EplusActivities.API/appsettings.json:/app/appsettings.json:ro
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        networks:
            - network-dapr
        restart: always
    eplusactivities-sidecar:
        image: daprio/daprd:edge
        container_name: EplusActivities-Sidecar
        command:
            [
                "./daprd",
                "-app-id",
                "EPlusActivities",
                "-app-port",
                "80",
                "-dapr-http-port",
                "3500",
                "-placement-host-address",
                "placement:50006",
                "-components-path",
                "/components",
            ]
        # "-config",
        # "/configurations/config.yaml",
        volumes:
            - ./Dapr/Components/:/components:ro
            - ./Dapr/Configurations/:/configurations:ro
        depends_on:
            - "eplusactivities-api"
        network_mode: service:eplusactivities-api
        restart: always

    ############################
    # FileService service
    ############################
    fileservice-db:
        image: mysql:8.0.25
        container_name: MySQL-FileService
        ports:
            - 30304:3306
        environment:
            MYSQL_DATABASE: FileService
            MYSQL_USER: ngs
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TZ: Asia/Shanghai
        volumes:
            - ./MySQL/FileService:/var/lib/mysql
        networks:
            - network-dapr
        restart: always

    fileservice:
        image: kamasylvia/fileservice:20211201
        container_name: FileService
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:52500
        ports:
            - 52500:52500
        links:
            - fileservice-db
        depends_on:
            - fileservice-db
            - placement
        volumes:
            - ./Logs/FileServiceLogs:/app/Logs
            - ./Settings/FileService/appsettings.json:/app/appsettings.json
            - ./FileStorage:/app/FileStorage
            - ./StaticFileStorage:/app/wwwroot
        networks:
            - network-dapr
        restart: always
    fileservice-sidecar:
        image: daprio/daprd:edge
        container_name: FileService-Sidecar
        command:
            [
                "./daprd",
                "-app-id",
                "FileService",
                "-app-port",
                "52500",
                "-app-protocol",
                "grpc",
                "-placement-host-address",
                "placement:50006",
                "-components-path",
                "/components",
            ]
        # "-config",
        # "/configurations/config.yaml",
        volumes:
            - ./Dapr/Components/:/components:ro
            - ./Dapr/Configurations/:/configurations:ro
        depends_on:
            - "fileservice"
        network_mode: service:fileservice
        restart: always

    ############################
    # Nginx service
    ############################
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 52537:52537
        links:
            - "eplusactivities-api"
        volumes:
            - ./Nginx/conf.d:/etc/nginx/conf.d:ro
            - ./html:/usr/share/nginx/html
            - ./Logs/NginxLogs:/var/log/nginx
        networks:
            - network-dapr
        restart: always

    ############################
    # Dapr placement service
    ############################
    placement:
        image: "daprio/dapr"
        command: ["./placement", "-port", "50006"]
        ports:
            - "50006:50006"
        networks:
            - network-dapr
    ############################
    # Redis state store
    ############################
    redis:
        image: "redis:alpine"
        ports:
            - "6380:6379"
        networks:
            - network-dapr
networks:
    network-dapr:
