version: "3.4"

services:
    db:
        image: mysql:8.0.25
        container_name: mysql
        environment:
            MYSQL_DATABASE: EPlusActivities
            MYSQL_USER: ngs
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - 3306:3306
        volumes:
            - ./MySQL:/var/lib/mysql
        restart: always

    webapi:
        image: kamasylvia/eplusactivities:20210820
        container_name: eplusactivities
        environment:
            # - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
        depends_on:
            - db
        links:
            - db
        ports:
            - 52537:80
        volumes:
            - ./Logs:/app/LogFiles
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
